server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: measurement-route
          uri: lb://MEASUREMENT-SERVICE
          predicates:
            - Path=/api/v1/quantities,/api/v1/quantities/**

        - id: auth-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: oauth2-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/oauth2/**,/login/**

        - id: user-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users,/api/users/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true