server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      # Enable service discovery with lowercase support
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: measurement-route
          uri: lb://measurement-service
          predicates:
            - Path=/api/v1/quantities,/api/v1/quantities/**

        - id: auth-route
          uri: lb://user-service
          predicates:
            - Path=/auth/**

        - id: oauth2-route
          uri: lb://user-service
          predicates:
            - Path=/oauth2/**,/login/**

        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/api/users,/api/users/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true