# MySQL Database Configuration

spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement
spring.datasource.username=root
spring.datasource.password=1210@Kash

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (optional but safe to keep)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true