server:
  port: ${PORT:8082}

spring:
  application:
    name: user-service

  # datasource (local) — comment hi rehne do
  # datasource:
  #   url: ${DB_URL:jdbc:mysql://localhost:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
  #   username: ${DB_USERNAME:root}
  #   password: ${DB_PASSWORD:password}
  #   driver-class-name: com.mysql.cj.jdbc.Driver

  # ✅ Railway DB (active)
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:23313/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: yEQwYmJsYTegHunUdbgAxxjDnOihNWxS
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true